choose_language = "×©×œ×•× {0}, ×× × ×‘×—×¨ ×©×¤×”.\nHello {0}, choose your language please."
[hebrew]
    welcome_to_the_group = "×©×œ×•× {0} ×•×‘×¨×•×›×™× ×”×‘××™× ×œ×§×‘×•×¦×”!\n×¢×•××“×™× ×œ×¨×©×•×ª×š {1} ×©× ×™×•×ª ×œ×œ×—×•×¥ ×¢×œ ×”×›×¤×ª×•×¨ ×œ××©×¨ ×©××ª×” ×œ× ×‘×•×˜ ;)\n×‘××™×“×” ×•×œ× ×œ×—×¦×ª, ×œ××—×¨ {1} ×©× ×™×•×ª ×ª×™×—×¡× ××”×§×‘×•×¦×”."
    message_not_for_you = "×× ×™ ××“××™×™×Ÿ ××• ×©×”×”×•×“×¢×” ×”×–×• ×œ× ×¤×•× ×” ××œ×™×š?ğŸ§"
    welcome = "×‘×¨×•×š ×”×‘×!"
    bye = "× ×—×¡××ª :("
    i_am_a_bot = "×× ×™ ×‘×•×˜ ğŸ¤–"
    i_am_a_human = "×× ×™ ×‘×Ÿ ××“× ğŸ‘¨"
    features = ["×›×¤×ª×•×¨ '×× ×™ ×‘×Ÿ ××“×' ×œ×–×™×”×•×™ ×‘×•×˜×™×."]
    bot_was_added = "@jinja ×”×™×™, ×× ×™ GroupManagerILBot ×•×× ×™ ××¢×–×•×¨ ×œ×›× ×‘× ×™×”×•×œ ×”×§×‘×•×¦×”. ×¢×œ ×× ×ª ×œ×”×’×“×™×¨ ××•×ª×™ ×™×© ×œ×œ×—×•×¥ ×¢×œ ×”×›×¤×ª×•×¨ ×œ××˜×”, ×¢×“ ××– ×× ×™ ×œ× ××¢×‘×•×“. \n\n××” ×× ×™ ××¦×™×¢ ( ×‘× ×ª×™×™× ) :\n{{'â€¢'+this.hebrew.features | join('\nâ€¢')}}"
    button_config = "×œ×—×¥ ×›××Ÿ ×œ×”×’×“×¨×”"
    language_has_been_changed = "×”×©×¤×” ×©×•× ×ª×” ×‘×”×¦×œ×—×”!"

[english]
    features = ["An 'I am a human' button to prevent spam"]
    bot_was_added = "@jinja Hi, I am GroupManagerILBot and i can help you to to manage your group and to prevent spam. \nIn order to set me up you need to click on the button below and follow the steps. \n Currently the only things I can do are: {{'â€¢'+this.english.features|join('\nâ€¢')}}"
    language_has_been_changed = "The language has been changed successfully"
    button_config = "Press here to set up"
    welcome_to_the_group = "Hello {0} and welcome to the group!\n You have {1} seconds to press the right button. Otherwise, you will be banned within {1} seconds."
    message_not_for_you = "Who are you?ğŸ§"
    welcome = "Welcome!"
    bye = "You got banned :("
    i_am_a_bot = "I am a bot ğŸ¤–"
    i_am_a_human = "I am a human ğŸ‘¨"