choose_language = "×©×œ×•× {0}, ×× × ×‘×—×¨ ×©×¤×”.\nHello {0}, choose your language please."
bot_was_added = "@jinja ×”×™×™, ×× ×™ GroupManagerILBot ×•×× ×™ ××¢×–×•×¨ ×œ×›× ×‘× ×™×”×•×œ ×”×§×‘×•×¦×”. ×¢×œ ×× ×ª ×œ×”×’×“×™×¨ ××•×ª×™ ×™×© ×œ×œ×—×•×¥ ×¢×œ ×”×›×¤×ª×•×¨ ×œ××˜×”, ×¢×“ ××– ×× ×™ ×œ× ××¢×‘×•×“. \n\n××” ×× ×™ ××¦×™×¢ ( ×‘× ×ª×™×™× ) :\n{{'â€¢ '+this.hebrew.features | join('.\nâ€¢ ')}}\n\n\nHi, I am GroupManagerILBot and i can help you to to manage your group and to prevent spam. \nIn order to set me up you need to click on the button below and follow the steps. \n\nCurrently the only things I can do are:\n {{'â€¢ '+this.english.features|join('.\nâ€¢ ')}}"
button_config = "×œ×—×¥ ×›××Ÿ ×œ×”×’×“×¨×” | Press here to set up"
welcome_to_bot_new = "Hi {0}, and welcome to {1}.\nPress the buttons below to change your language.\n\n\n ×©×œ×•× {0} ×•×‘×¨×•×›×™× ×”×‘××™× ×œ {1}, ×‘×‘×§×©×” ×ª×œ×—×¥ ×¢×œ ×”×›×¤×ª×•×¨×™× ×œ××˜×” ×¢×œ ×× ×ª ×œ×©× ×•×ª ××ª ×”×©×¤×”."

[hebrew]
    welcome_to_the_group = "×©×œ×•× {0} ×•×‘×¨×•×›×™× ×”×‘××™× ×œ×§×‘×•×¦×”!\n×¢×•××“×™× ×œ×¨×©×•×ª×š {1} ×©× ×™×•×ª ×œ×œ×—×•×¥ ×¢×œ ×”×›×¤×ª×•×¨ ×œ××©×¨ ×©××ª×” ×œ× ×‘×•×˜ ;)\n×‘××™×“×” ×•×œ× ×œ×—×¦×ª, ×œ××—×¨ {1} ×©× ×™×•×ª ×ª×™×—×¡× ××”×§×‘×•×¦×”."
    message_not_for_you = "×× ×™ ××“××™×™×Ÿ ××• ×©×”×”×•×“×¢×” ×”×–×• ×œ× ×¤×•× ×” ××œ×™×š?ğŸ§"
    welcome = "×‘×¨×•×š ×”×‘×!"
    bye = "× ×—×¡××ª :("
    i_am_a_bot = "×× ×™ ×‘×•×˜"
    i_am_a_human = "×× ×™ ×‘×Ÿ ××“×"
    features = ["×›×¤×ª×•×¨ '×× ×™ ×‘×Ÿ ××“×' ×œ×–×™×”×•×™ ×‘×•×˜×™×"]
    language_has_been_changed = "×”×©×¤×” ×©×•× ×ª×” ×‘×”×¦×œ×—×”!"
    refresh_admins = "×¨×¢× ×Ÿ ×¨×©×™××ª ×× ×”×œ×™×"
    available_commands = ["/admins - ×¦×¤×™×” ×•×¨×™×¢× ×•×Ÿ ×¨×©×™××ª ×”×× ×”×œ×™× ×‘×‘×•×˜", "/language - ×©×™× ×•×™ ×”×©×¤×” ×‘×‘×•×˜"]
    welcome_to_panel  = "@jinja ×‘×¨×•×š ×”×‘× ×œ×¤×× ×œ ×”× ×™×”×•×œ!\n×œ×¤×× ×œ ×–×” ×¨×§ ×× ×”×œ×™× ××•×¨×©×™× ×™×›×•×œ×™× ×œ×”×™×›× ×¡ (×‘×‘×¨×™×¨×ª ××—×“×œ - ×›×œ ×”×× ×”×œ×™×) ×•×¤×” × ×™×ª×Ÿ ×œ×¢×¨×•×š ××ª ×”×”×’×“×¨×•×ª ×©×œ ×”×§×‘×•×¦×”.\n\n\n××¤×©×¨×•×™×•×ª ×–××™× ×•×ª:\n{{ this.hebrew.available_commands | join('.\n') }}"
    welcome_to_the_bot = "@jinja  ×‘×¨×•×›×™× ×”×‘××™× ×œ {}, \n\n\n××¤×©×¨×•×™×•×ª ×–××™× ×•×ª:\n{{ this.hebrew.available_commands | join('.\n') }}"

[english]
    features = ["An 'I am a human' button to prevent spam"]
    language_has_been_changed = "The language has been changed successfully"
    welcome_to_the_group = "Hello {0} and welcome to the group!\n You have {1} seconds to press the right button. Otherwise, you will be banned within {1} seconds."
    message_not_for_you = "Who are you?ğŸ§"
    welcome = "Welcome!"
    bye = "You got banned :("
    i_am_a_bot = "I am a bot"
    i_am_a_human = "I am a human"
    refresh_admins = "Refresh admins list"
    available_commands = ['/admins - watch and refresh your admins list', '/language - set up your language in the bot']
    welcome_to_panel = "@jinja Welcome to the administration panel!\nOnly allowed admins can use this panel (By default - every admin), and here you can edit your group configuration.\n\n\nAvailable options:\n {{ this.english.available_commands | join('.\n') }}"
    welcome_to_the_bot = "@jinja Welcome to {}, \n\n\nAvailable options:\n {{ this.english.available_commands | join('.\n') }}"